### PR TITLE
feat(blog): building a blog environment using honox

### PR DESCRIPTION
**Pull request by yossydev**
I don't know how this repository operates, so you don't have to merge this PR right away!
You can use this PR to handle all of your blogging needs, or you can merge it first! I leave it up to you!

## Overview
At first, I tried to build the environment.
I ran `npm create hono@latest`, `pnpm install && pnpm dev` and confirmed that http://localhost:5173/ is up and running!

## Consultation
Should I make it possible to run blog with docker?
Personally, I don't think it's particularly necessary to run it with docker, so I haven't made any special settings. If it is necessary, I will respond!

## Related
- https://github.com/honojs/honox
- #10

### CODE REVIEW

**Comment by yossydev** [comment]
Hi flipvh! Roger that! I'll continue this PR as is!
I will try to set up the environment needed to create the site and also create a simple UI using https://www.loglib.io/blog as a reference!

**Comment by yossydev** [comment]
> About your question in the issue concerning hosting. Yes for hosting we currently use render.com. It hosts all that we need: db, static site, our api and our tus server for file uploading. However, I'd like to also try cloudflare and perhaps even fly.io. But didn't find time for that yet

Understood! I'm not in a hurry at all, so take your time! Thanks for letting me know! 🙇‍♂️

**Comment by yossydev** [comment]
I was looking around a bit at things at hand and found that shadcn/ui depends on react, so I was able to get it to work, although I had to configure it a bit to use HonoX!

https://github.com/yossydev/honox-shadcn

**Comment by yossydev** [comment]
I was able to get the blog to display in SSR! I think this completes the environment setup area!
One concern is that I would have liked to do it using SSG if I could, but once I got the error `TypeError: __vite_ssr_import_0__.jsxDEV is not a function` and the mdx is not properly parsed, I am now using SSR. I will look into this when I have time!

Next I'm going to work on the UI area! It's a simple one!

- [feat(blog): building a blog environment using honox](https://github.com/cellajs/cella/pull/11/commits/818d884c994fd2c899b5b37363ca2530907dc600)
- [feat: use react-renderer to make shadcn/ui work](https://github.com/cellajs/cella/pull/11/commits/c8f9f078595d203ba43458c15a4c4b4886a3358b)
- [feat: Display your blog on SSR.](https://github.com/cellajs/cella/pull/11/commits/607a99fc15cd9ff1215fdcd27de30ede54fe242c)

**Comment by yossydev** [comment]
Hi @flipvh👋

> I will share some visuals for the blog design later.
> comment: https://github.com/cellajs/cella/issues/10#issuecomment-2006311344

Have you decided on a design for your blog yet? 👀

**Comment by flipvh** [comment]
thnks for the reminder. I borrowed the style from a friend a bit (https://mave.io). 

The wrapper elements are basically the same as those used for the pages in /frontend/src/modules/marketing. For example https://cellajs.com/accessibility shows this. You can see the main wrapping component that is used for that page here: https://github.com/cellajs/cella/blob/main/frontend/src/modules/common/public-page.tsx


See the attachments 
overview
post

**Comment by flipvh** [comment]
Hope that helps @yossydev! let me know if you need more or have questions! PS: did you manage to get cella running on your local machine? We are looking for feedback on how to make this more convenient or easy. Exciting!

**Comment by yossydev** [comment]
Thank you, I will try to get a copy of the article! Now that I have the UI, all I have to do is make it! It helps!
comment: https://github.com/cellajs/cella/pull/11#issuecomment-2024715544

I built the environment first and didn't touch the rest! 🙏
I will try to touch it and if I find anything I will definitely let you know! I want to make cellajs better too!
comment: 
Hope that helps @yossydev! let me know if you need more or have questions! PS: did you manage to get cella running on your local machine? We are looking for feedback on how to make this more convenient or easy. Exciting!

**Comment by yossydev** [comment]
I'm working on an implementation, but I'm afraid that if I try to use the components in `/frontend`, I'll end up with a lot of packages that depend on it, and that will pretty much eliminate all the goodness of `HonoX`.
So I think I'll just refer to the style. However, I'm a little concerned that this will result in two components with similar styles, which will reduce maintainability.

I'll also try to read some more code in `/frontend`. If I understand more of the `cellajs` philosophy, can I contribute to the blog as well as other parts of the site?

**Comment by yossydev** [comment]
Hi @flipvh 👋

I'm trying to launch `cellajs`, but I'm encountering an error when using `docker`. Do you know what could be the cause of this? I'm trying to run `pnpm run docker` without making any edits on the main branch. The first method of `pnpm install` didn't work for me because I'm using [mise](https://github.com/jdx/mise) instead of Volta for node version management.

```bash
> cella@0.1.0 docker /Users/yy/Desktop/cella
> docker-compose --env-file env/.env up

[+] Running 4/0
 ✔ Container db        Created                                                                                                                                                                                                          0.0s
 ✔ Container frontend  Created                                                                                                                                                                                                          0.0s
 ✔ Container tus       Created                                                                                                                                                                                                          0.0s
 ✔ Container backend   Created                                                                                                                                                                                                          0.0s
Attaching to backend, db, frontend, tus
db        |
db        | PostgreSQL Database directory appears to contain a database; Skipping initialization
db        |
db        | 2024-04-01 16:10:36.435 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db        | 2024-04-01 16:10:36.435 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db        | 2024-04-01 16:10:36.435 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db        | 2024-04-01 16:10:36.438 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db        | 2024-04-01 16:10:36.444 UTC [29] LOG:  database system was shut down at 2024-04-01 16:09:55 UTC
db        | 2024-04-01 16:10:36.449 UTC [1] LOG:  database system is ready to accept connections
tus       |
tus       | > tus@1.0.0 dev /app/tus
tus       | > NODE_ENV=development tsup --watch --onSuccess "tsx dist/index.cjs"
tus       |
frontend  |
frontend  | > frontend@0.0.1 dev /app/frontend
frontend  | > NODE_ENV=development vite --mode development
frontend  |
frontend  | node:internal/modules/cjs/loader:1147
frontend  |   throw err;
frontend  |   ^
frontend  |
frontend  | Error: Cannot find module '/app/frontend/node_modules/vite/bin/vite.js'
frontend  |     at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
frontend  |     at Module._load (node:internal/modules/cjs/loader:985:27)
frontend  |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
frontend  |     at node:internal/main/run_main_module:28:49 {
frontend  |   code: 'MODULE_NOT_FOUND',
frontend  |   requireStack: []
frontend  | }
frontend  |
frontend  | Node.js v20.11.1
frontend  |  ELIFECYCLE  Command failed with exit code 1.
backend   |
backend   | > backend@0.0.1 migrate:script /app/backend
backend   | > tsx dist/src/db/migrate.cjs
backend   |
backend   | node:internal/modules/cjs/loader:1147
backend   |   throw err;
backend   |   ^
backend   |
backend   | Error: Cannot find module '/app/backend/node_modules/tsx/dist/cli.mjs'
backend   |     at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
backend   |     at Module._load (node:internal/modules/cjs/loader:985:27)
backend   |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
backend   |     at node:internal/main/run_main_module:28:49 {
backend   |   code: 'MODULE_NOT_FOUND',
backend   |   requireStack: []
backend   | }
backend   |
backend   | Node.js v20.11.1
backend   |  ELIFECYCLE  Command failed with exit code 1.
frontend exited with code 0
tus       | CLI Building entry: src/index.ts
tus       | CLI Using tsconfig: tsconfig.json
tus       | CLI tsup v8.0.2
tus       | CLI Using tsup config: /app/tus/tsup.config.ts
tus       | CLI Running in watch mode
tus       | CLI Target: es2020
tus       | CLI Cleaning output folder
tus       | CJS Build start
tus       | CJS dist/index.cjs     768.00 B
tus       | CJS dist/index.cjs.map 1.08 KB
tus       | CJS ⚡️ Build success in 25ms
tus       | CLI Watching for changes in "."
tus       | CLI Ignoring changes in "**/{.git,node_modules}/**" | "dist"
```

**Comment by flipvh** [comment]
Hi @yossydev let me check it out and thnks for your interest in cella. It would be great if you can help us out with cella itself too if you see opportunities there. Actually, we don't use Docker ourselves so its a bit easy to forget about checking if that flow still works. But I will do so now. I also plan to support a serverless Postgres solution ( like Neon or Supabase) so it becomes easier to just install without having to run postgres locally.

**Comment by yossydev** [comment]
Hi @flipvh 👋

This is a consultation, but what about DI the logic of `/frontend` components to be received by props? (so called container/presentation way of making it).
I think doing this would allow testing with storybooks and make cellajs blogging much easier!

Currently, it depends on various libraries, especially the dependency on `tanstack-router` is a bit troublesome, and `HonoX` is not a good match since it is file system routing. I'm thinking that if things stay as they are, I'll need to create two components with the same UI.

I feel like a little bit of test code would make it a better template.

**Comment by flipvh** [comment]
Hi @yossydev that sounds interesting. To be sure I understand correctly can you give small examples? 

Yes, testing is on our roadmap, we are indeed looking at storybook, vitest and playwright. We currently use [pivotal tracker](https://www.pivotaltracker.com/n/projects/2683224) to manage issues/tickets, you can see a story about starting with testing here: https://www.pivotaltracker.com/story/show/186816158

And about storybook I am following this PR: https://github.com/shadcn-ui/ui/pull/1561

Thanks!!

**Comment by yossydev** [comment]
OK, I'll put out a PR later!

**Comment by yossydev** [comment]
Hi @flipvh 👋
I was talking about writing a storybook the other day and trying things out, but it seemed quite complicated and time-consuming, so I decided to make a blog first!

And once I've done that, I've got the look and feel of the home page! The code is not very maintainable, so I'll fix that later!

Next, I want to make a blog detail page, but if Hono's `react-renderer` middleware doesn't seem to support nested layout, I'll make a PR on the `Hono` side, so please wait a bit! It shouldn't be that difficult though!

Sorry for the late implementation!


localhost_5173_

↑ This is the top page UI we created!

**Comment by flipvh** [comment]
That looks like great progress. Well done!

**Comment by yossydev** [comment]
Nested Layout in react-renderer implemented in hono's middleware!(https://github.com/honojs/middleware/releases/tag/%40hono%2Freact-renderer%400.2.0) 
And I actually used it on this blog and it worked! This blog will probably be ready this weekend!

**Comment by flipvh** [comment]
No rush @yossydev, but thanks for the update!

**Pull request closed without merging**
